### ISSUE TITLE
Getting Involved

### ISSUE THREAD

**Issue by ngoduykhanh** [gitops-working-group/gitops-working-group#23]
Hi,

I am interested in this topic as well and wanted to contribute. How to get started? I already filled my name in the Google Docs file.

**Comment by todaywasawesome** [comment]
Great! I think I already saw you on the Slack but otherwise you can join below. 

**Suggestions for participating**: 
- If you haven't already joined the slack it's the [CNCF slack](https://slack.cncf.io/) #wg-gitops
- ~~Add your info to the [interest doc](https://docs.google.com/document/d/11EZfvB2FFI837nMmArnyv-wizsIJvc-4_xdgfoUXF4o/edit)~~
- Join [upcoming meetings](https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md)
