### ISSUE TITLE
Create website

### ISSUE THREAD

**Issue by alisondy** [gitops-working-group/gitops-working-group#89]
Create a website for the project

Fork `https://github.com/cncf/hugo-netlify-starter` to `gitops-working-group/website`

Site Structure

 📌   📄   Home
 - Big Intro block
 - GitopsCon Callout block
 - Get Involved Callout block
 - Participating Organisations block with logos of orgs

📌   About
📄   About this open gitops,
- goals
- roadmap

📄   Leadership

📌   Get Involved
📄   participate
📄   workstreams
📄   meeting calendar
 
📌   Resources
📄   GitOps Definition
📄   GitOps Principles
📄   Case Studies

📌   Blog

📌   Events
📄   GitOpsCon 2021

📌  📄   FAQs
- What is OpenGitops About
 
 Other thoughts
 🎨  Create theme for website
 
 Segmenting this issue up
 - create an issue for the forking of the repo
 - create issues for the pages ( could be some good potential first issues )
 
 references
 - inclusive naming website, https://inclusivenaming.org/
 - initial sketchup of idea, https://miro.com/app/board/o9J_lNwUWws=/

**Comment by alisondy** [comment]
https://github.com/orgs/gitops-working-group/projects/4#card-57138689

Just following up, I just found the cards in the project boards

GitHub Project cards are challenging to search for, and don't appear in normal issue searches

Recommend making github issues for better visibility

**Comment by scottrigby** [comment]
@alisondy 

> Recommend making github issues for better visibility, and accessibility

I agree, project boards are helpful, but the note card option should only be temporary placeholders for what should become issues once they're fleshed out to be more than just a note. Once they're issues, like you said people can comment 👍 

I added an item to the [next WG meeting agenda](https://docs.google.com/document/d/1hxifmCdOV5_FbKloDJRWZQHq0ge-trXJKF-BgV4wHVk/edit#heading=h.zekmcm7llerh) to discuss, and make sure people are aware of how our GH project boards fit into this accessibility goal.

Also, now that https://github.com/gitops-working-group/gitops-working-group/pull/84 was merged, there is a link to project boards under [How To Get Involved](https://github.com/gitops-working-group/gitops-working-group/blob/main/README.md#how-to-get-involved), so that should help with visibility too.

**Comment by scottrigby** [comment]
Also see https://github.com/gitops-working-group/gitops-working-group/issues/111

**Comment by todaywasawesome** [comment]
@alisondy Work has begun! I've got a designer working on the look/feel which I'll share with everyone on Slack. In the meantime here's the basic architecture for people to start filling content onto https://docs.google.com/document/d/14B-t0Y4rMFQ_pcDGjecicxn9ZcpssrOSlqIKbuWwtaM/edit

**Comment by todaywasawesome** [comment]
Closing in favor of [159](https://github.com/gitops-working-group/gitops-working-group/issues/159)
