### ISSUE TITLE
Set up GitHub teams to allow people to help with various needs for the GitOps WG, without giving away keys to the kingdom.

### ISSUE THREAD

**Issue by scottrigby** [gitops-working-group/gitops-working-group#98]
Reasoning:
- 🚫 Repo-level project boards require `Maintain` access in a repo
- ✅ Org-level project boards can require only org or team membership

**Comment by lloydchang** [comment]
@scottrigby I don't fully understand the summary and description because they don't explain the context of access control avenue.

Context wise, which access control avenue are you referring to?
1. outside collaborator
2. individual
3. team membership
4. organization membership

For example:
> Note: If a person has multiple avenues of access to an organization project board (individually, through a team, or as an organization member), the highest project board permission level overrides lower permission levels. For more information, see "Project board permissions for an organization."
https://docs.github.com/en/organizations/managing-access-to-your-organizations-project-boards/managing-an-individuals-access-to-an-organization-project-board

Thank you.

**Comment by scottrigby** [comment]
This was from a working group meeting last year. We were being solutions-focused, and it worked well for what we needed then. As far as I know no one was blocked. That said, the biggest challenge is coordinating tasks between team members and actually getting the things done.
